### ISSUE TITLE
[Feature Request] cdb support

### ISSUE THREAD

**Issue by Stolas** [snare/voltron#113]
An idea I was playing with was cdb support  for Voltron.

cdb is the console based windbg, and as windbg can load python addons I thought Voltron might be a great addition.

I have been thinking for over a month to implement this myself, although it seems I don't have enough spare time to get  started with it. Decided to dump the idea here so everybody can comment on the idea and or implement it.

**Comment by snare** [comment]
I haven't used cdb, but I actually implemented the majority of the necessary code for WinDbg recently. I haven't finished it, but I will try to get it finished and pushed out soon.

AFAIK WinDbg only supports loading Python scripts with `pykd`, is that the same for cdb?

One problem with WinDbg is I can't find any equivalent for the stop hook mechanism that GDB and LLDB implement. Voltron relies on this to know when to process requests and update views. The way I was thinking about working around this was to resurrect `voltron console` but rather than a layer on top of LLDB like it was, build a CLI that just acts as a REPL with command requests being sent to the Voltron server and the output displayed in the REPL. That way there's an easy way to know when to update the views.

**Comment by Stolas** [comment]
The power of open source, great to hear you have almost finished it :+1:  AFAIK cdb is the exact same as windbg but as a console version. If you'd push it into a different branch, I can look into the issue with the hooking mechanism.

**Comment by snare** [comment]
Pushed to the windbg branch. There's some bits that aren't implemented/still have code from the GDB version that I copied. See [here](https://github.com/snare/voltron/blob/windbg/voltron/plugins/debugger/dbg_windbg.py) for the debugger adaptor for WinDbg.

To use it currently, you need to install the voltron package, then in WinDbg:

    .load pykd.pyd
    !py
    >>> import voltron.entry;voltron.init()

If you try to `!py /path/to/entry.py` it seems to hang the debugger the next time you do something. I only barely got it working so YMMV, but feel free to take a look :)

Oh you'll also need to install a binary package of `curses` for Windows Python. I can't remember where I found the one I used.

**Comment by williballenthin** [comment]
I'm pretty keen on this as well, so I'll be around to do testing as code becomes available :-)

**Comment by snare** [comment]
Awesome, thanks guys :)

**Comment by snare** [comment]
Also, once Voltron is loaded into WinDbg you *should* be able to:

    $ python
    >>> import voltron
    >>> c = voltron.core.Client()
    >>> c.perform_request('version')

Or, if you also `pip install voltron-web` you should be able to go to http://127.0.0.1:5555 in your browser and use the web UI for sending test requests. It doesn't work for me in IE (probably due to the localhost thing that IE has and I can't remember because I don't really do Windows), but it works in Chrome. Actually sending blocking requests - not so much, but hopefully we can fix that.

**Comment by snare** [comment]
@ussrhero on twitter pointer me at his project `karmadbg` which is based on `pykd` and does some event handling stuff that might be useful for command prompt hooks

http://karmadbg.codeplex.com/SourceControl/latest#karmadbg/dbgcore/nativedbg.py

**Comment by snare** [comment]
Also you guys might find Karma useful :)

**Comment by snare** [comment]
OK, WinDbg/CDB support is pretty much there.

![image](https://cloud.githubusercontent.com/assets/504561/14402528/f89d680e-fe7b-11e5-9cf0-e0ee132ab8e3.png)

I just need to add a Pygments lexer for the disassembly, and fix a few little bugs (like the rendering of unicode strings you can see in the stack view there).

View updating was actually super easy thanks to PyKD's event handlers, so no need to resort to replicating the console within Voltron. I'll merge this shortly and push it out.

**Comment by snare** [comment]
Merged and pushed to master. Let me know how it goes :)

**Comment by Stolas** [comment]
Great, will test it when I've got the chance!

**Comment by snare** [comment]
Whoops, lexer for disassembly is still outstanding.

**Comment by williballenthin** [comment]
Got this working today. The most difficult part was getting the `blessed` package working, since it depends on `curses`, which doesn't easily work on Windows. For future reference, I used the package here:

http://www.lfd.uci.edu/~gohlke/pythonlibs/#curses

![voltron-win](https://cloud.githubusercontent.com/assets/156560/15123312/3bb184d6-15f1-11e6-821e-51454923708c.png)

**Comment by snare** [comment]
Awesome thanks man. I think I used that same binary. I'll put a link to it in the Windows page on the wiki. Glad to see someone using Calculon too :) I've been rewriting it over the last few days.

**Comment by snare** [comment]
I'm considering rewriting the views to use Urwid which will remove the curses dependency, but I'm not 100% sold on it yet.

**Comment by snare** [comment]
Added lexer in 4a0b451a2eb3b9d113b5270a1a821f785e33ce96
