### ISSUE TITLE
Add option for install.sh

### ISSUE THREAD

**Issue by NoAnyLove** [snare/voltron#166]
It is better to add an option to decide to install Voltron for gdb or lldb, when both of them are exising.

BTW, I think install.sh should also add `setttings set target.x86-disassembly-flavor intel` to ~/.lldbinit, as the default asm flavor of lldb is not Intel style.

**Comment by snare** [comment]
Yep good call, thanks.

**Comment by snare** [comment]
I actually probably won't do this because I'd rather not enforce that people use Intel syntax. If they're already using Intel syntax then great, if they're not they can manually change it per the documentation, but I'd rather not be automatically changing it if people are already happily using AT&T syntax. I will add a lexer for AT&T syntax soon.

**Comment by snare** [comment]
Re: installing for only one debugger, I will add some interactivity to the install script so you can choose which debugger(s) to install for.
