### ISSUE TITLE
Using voltron hangs Xcode

### ISSUE THREAD

**Issue by sloik** [snare/voltron#230]
My .lldbinit looks like this:

```
command script import ~/Library/Python/2.7/lib/python/site-packages/voltron/entry.py
```

When I have a breakpoint in Xcode 9.2 (9C40b) and its getting hit no lldb prompt is shown and nothing happens. There's a  spinner in the "raport navigator" and on top there's a message "Attaching to Project on SimulatorName". Attaching thru "terminal" works fine.

**Comment by sarangkarandikar1** [comment]
Doesn't work due to bug in LLDB library. If you want voltron enabled only for command line, use `command script .../entry.py` in `.lldbinit-lldb` and Xcode stuff only in `lldbinit-Xcode`.

**Comment by sarangkarandikar1** [comment]
If you want to dig in, build LLDB library manually by applying this patch, and link output directory from/ to `/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/Current`. 

* You would need to run codesign on a bunch of binaries which loads LLDB library to remove their signatures so that this unsigned binary runs.
* I linked relevant Xcode bits and copied ones which I changed.
* Some xcrun initiated system commands would fail to run, I just revert the `/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/Current` to link to original `A` folder.
* Use at your own risk :).

Add this change:
```
--- IOHandler.cpp	(revision 328037)
+++ IOHandler.cpp	(working copy)
@@ -380,7 +380,32 @@
       bool done = false;
       bool got_line = false;
       m_editing = true;
+
+#define WITH_SELECT_FIX
+
+#ifdef WITH_SELECT_FIX
+      // Should do this somewhere else.
+      signal(SIGPIPE, SIG_IGN);
+
+      auto fd_in = fileno(in);
+      bool is_tty = isatty(fd_in);
+#endif
+
       while (!done) {
+
+#ifdef WITH_SELECT_FIX
+
+        if (is_tty)
+        {
+          fd_set inset;
+          FD_ZERO(&inset);
+          FD_SET(fd_in, &inset);
+
+          select(fd_in+1, &inset, NULL, NULL, NULL);
+        }
+
+#endif
+
```

**Comment by sarangkarandikar1** [comment]
You still would need an Xcode restart every time process is restarted. #228 .

**Comment by sloik** [comment]
Than you :)
