### ISSUE TITLE
LLDB Can't Load Python's Module

### ISSUE THREAD

**Issue by haotianmichael** [snare/voltron#279]
I installed voltron successfully with `./install.sh -b lldb`
It automatically located python's version, which is `python3.8`, linked against with my lldb, and the installation processed well.
But I start lldb, it reported errors like:
```
An error occurred while loading Voltron:

Traceback (most recent call last):
  File "/Users/haotianmichael/Library/Python/3.8/lib/python/site-packages/voltron/entry.py", line 57, in <module>
    import voltron
  File "/Users/haotianmichael/Library/Python/3.8/lib/python/site-packages/voltron/__init__.py", line 6, in <module>
    from .main import main
  File "/Users/haotianmichael/Library/Python/3.8/lib/python/site-packages/voltron/main.py", line 9, in <module>
    from .view import *
  File "/Users/haotianmichael/Library/Python/3.8/lib/python/site-packages/voltron/view.py", line 25, in <module>
    from .core import Client
  File "/Users/haotianmichael/Library/Python/3.8/lib/python/site-packages/voltron/core.py", line 16, in <module>
    from flask import Flask, Response, make_response, redirect, render_template, request
ModuleNotFoundError: No module named 'flask'

Please ensure Voltron is installed correctly per the documentation: https://github.com/snare/voltron/wiki/Installation

```

I tapped python3.8 and imported flask, and it was good.
```
$ python3.8
$>>> import flask
$>>> 
```
And I ran `voltron` individually in its installed directory, and it didn't error ethier. 
```
$ voltron
usage: voltron [-h] [--debug] [-o O] {view,v} ...
voltron: error: the following arguments are required: subcommand
```
But why lldb can't load this? And I'm sure `python3.8` is default python version because voltron located it. No idea what's going on, any help will be appreciated! 
My machine:
*  Darwin Kernel Version 19.6.0(macOS Catalina)
*  lldb-1200.0.32.1  (Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1))
*  voltron

**Comment by zcutlip** [comment]
I do think though, that if you have a collection of mixed & matched `dataclass` types, there may be no solution, because for those, `dacite` needs to know the classes explicitly in order to instantiate them

So if we had:
```
@dataclass
class MyDC:
    stuff: Dict[Any, Any]

@dataclass
class MyOtherDC:
    pass

@dataclass
class MyOtherOtherDC:
    pass

my_dataclass_thing_1 = MyOtherDC()
my_dataclass_thing_2 = MyOtherOtherDC()
```

And `stuff` looked like:
```
{
    "my_other_dc": my_dataclass_thing_1,
    "my_other_other_dc": my_dataclass_thing_2
}
```

Then `dacite` won't be able to work out from the `(Any, Any)` type tuples what object types to instantiate.

So a collection of mixed types just isn't possible if any of the types are `dataclass`es, if I'm not mistaken.

**Comment by zcutlip** [comment]
Apologies for the delay getting to this issue.

I'm not able to reproduce the problem.

Can you share output from a couple of things?

1. In your python3.8 REPL as above, can you share the output of:
```
>>>import flask
>>>flask.__file__
```
2. What python version your LLDB has embedded:
```
$ lldb -Q -x -b --one-line 'script import sys; print(sys.executable)'
```
3. What your lldb thinks its python executable is:
```
$ lldb -Q -x -b --one-line 'script import sys; print(sys.executable)
```
4. What happens if you try to manually import flask in LLDB:
```
(lldb) script
>>> import flask
>>> flask.__file__
``` 

Thanks,
Zach

**Comment by haotianmichael** [comment]
Thanks for help~It seems a typical problem of multi-version of pythons in MacOS. Now been fixed!

**Comment by haotianmichael** [comment]
Thanks for help~It seems a typical problem of multi-version of pythons in MacOS. Now been fixed!
