### ISSUE TITLE
Use Relative Imports

### ISSUE THREAD

**Issue by 8BitAce** [snare/voltron#86]
Many of the Python modules import voltron itself, which requires a previous installation (or otherwise adding it to PYTHONPATH).

It might make more sense to use relative imports (e.g. `from .. import voltron`) so that it can be run as a self-contained entity.

I might be missing some downside though.

**Comment by snare** [comment]
Yeah that seems reasonable. When I wrote some of this I was fairly new to Python and sucked at understanding the relative import shiz. I'll give it a go some time and see how it goes.

**Comment by snare** [comment]
On second thought, the plugins are written in this way so that they can be used (assuming modified) in the user's `~/.voltron/plugins` dir, which will obviously not be inside the package. So I don't think I'll bother updating it to use relative imports everywhere. It gets ugly when you're 3 subpackages deep and just want `voltron.config` etc. I think it's reasonable to assume the user will install the package properly.
